//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 09:57:27 PM EEST 
//


package com.example.contacts;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="contact" type="{http://www.example.com/contacts}contactOnly" maxOccurs="unbounded"/>
 *           &lt;element name="contactWithBooks" type="{http://www.example.com/contacts}contactWithBooks" maxOccurs="unbounded"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "contact",
    "contactWithBooks"
})
@XmlRootElement(name = "getContactsResponse")
public class GetContactsResponse {

    protected List<ContactOnly> contact;
    protected List<ContactWithBooks> contactWithBooks;

    /**
     * Gets the value of the contact property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contact property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContact().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContactOnly }
     * 
     * 
     */
    public List<ContactOnly> getContact() {
        if (contact == null) {
            contact = new ArrayList<ContactOnly>();
        }
        return this.contact;
    }

    /**
     * Gets the value of the contactWithBooks property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactWithBooks property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContactWithBooks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContactWithBooks }
     * 
     * 
     */
    public List<ContactWithBooks> getContactWithBooks() {
        if (contactWithBooks == null) {
            contactWithBooks = new ArrayList<ContactWithBooks>();
        }
        return this.contactWithBooks;
    }

}
